<?php

use Pushwoosh\Web\Block\PushwooshWeb;

/**
 * @var PushwooshWeb $block
 */
$helper = $block->getHelper();
if (!$helper->isEnabled()){
    return;
}
?>

<script type="text/javascript" src="https://cdn.pushwoosh.com/webpush/v3/pushwoosh-web-notifications.js" async></script>
<script type="text/javascript">
    var Pushwoosh = Pushwoosh || [];
    var pushwooshConfig = {
        logLevel: 'info',
        applicationCode: "<?= $block->escapeHtml(__($helper->getApplicationCode())) ?>",
        apiToken: "<?= $block->escapeHtml(__($helper->getApiToken())) ?>",
        safariWebsitePushID: 'web.com.example.domain',
        defaultNotificationTitle: 'Pushwoosh',
        defaultNotificationImage: 'https://yoursite.com/img/logo-medium.png',
        scope: '/',
        serviceWorkerUrl: '/pushwoosh_web/serviceworker/index',
    }

    Pushwoosh.push(['init', pushwooshConfig]);
</script>
<script type="text/javascript">
    require([
        'jquery',
        'mage/url'
    ], function ($, urlBuilder) {
        'use strict';

        $.ajax({
            url: urlBuilder.build('pushwoosh_web/customeremail/index'),
            type: 'GET',
            dataType: 'json'
        }).done(function (data) {
            if (data.email) {
    Pushwoosh.push(['onReady', function(api){
                    api.registerUser(data.email);
    }]);
            }
        });
    });
</script>
