<?php
use \Omotech\AbandonedCart\Block\System\Config\SyncAbandonedCartData;

/**
 * @var OrderSyncStatus $block
 */
?>
<table cellspacing="0" class="form-list">
    <tbody>
    <tr>
        <td class="label"></td>
        <td class="value">
            <div class="messages">
                <div class="message message-notice" >
                    <div>
                        <?= $block->escapeHtml(__("Total Abandoned Carts :")) ?>
                        <strong><?= $block->escapeHtml(__($block->getTotalAbandonedCart())) ?></strong>
                    </div>
                </div>
            </div>
            <div class="messages">
                <div class="message message-notice" >
                    <div>
                        <?= $block->escapeHtml(__("Synced Abandoned Carts :")) ?>
                        <strong><?= $block->escapeHtml(__($block->getSyncAbandonedCart())) ?></strong>
                    </div>
                </div>
            </div>
            <div class="messages">
                <div class="message message-notice" >
                    <div>
                        <?= $block->escapeHtml(__("Not Synced Abandoned Carts :")) ?>
                        <strong><?= $block->escapeHtml(__($block->getNotSyncAbandonedCart())) ?></strong>
                    </div>
                </div>
            </div>
            <div class="messages">
                <div class="message message-notice" >
                    <div>
                        <?= $block->escapeHtml(__("Fail Synced Abandoned Carts :")) ?>
                        <strong><?= $block->escapeHtml(__($block->getFailedSync())) ?></strong>
                    </div>
                </div>
            </div>
        </td>
        <td class></td>
    </tr>
    </tbody>
</table>
